O aprendizado de máquina automatizado (AutoML) é o processo de automatizar as tarefas de aplicação do aprendizado de máquina a problemas do mundo real.  O AutoML visa simplificar essas etapas para não especialistas e facilitar o uso correto e eficaz das técnicas de aprendizado de máquina.




https://automl.github.io/auto-sklearn/master/api.html

https://automl.github.io/auto-sklearn/master/faq.html#faq

https://github.com/GauravSahani1417/Kaggle-Datasets/blob/master/Heart_failure_prediction_using_Auto_Sklearn_%F0%9F%A9%BA.ipynb

https://blog.dsbrigade.com/introducao-a-automl/


# **PRÉ-PROCESSAMENTO**

In [ ]:
!pip install auto-sklearn



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install scikit-learn==0.24.1


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 37.4 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.24.2
    Uninstalling scikit-learn-0.24.2:
      Successfully uninstalled scikit-learn-0.24.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.5 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.1 which is incompatible.
imbalanced-learn 0.10.1 requires scikit-learn>=1.0.2, but you have scikit-learn 0.24.1 which is incompatible.


In [ ]:
!pip install dask distributed --upgrade


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 26.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 951.2/951.2 KB 71.3 MB/s eta 0:00:00
  Attempting uninstall: dask
    Found existing installation: dask 2022.12.1
    Uninstalling dask-2022.12.1:
      Successfully uninstalled dask-2022.12.1
  Attempting uninstall: distributed
    Found existing installation: distributed 2022.12.1
    Uninstalling distributed-2022.12.1:
      Successfully uninstalled distributed-2022.12.1


In [ ]:
import autosklearn
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import autosklearn.regression
from autosklearn.classification import AutoSklearnClassifier
import numpy as np

In [ ]:
df = pd.read_csv('/content/sal_pocos (1) (3).csv',
                  sep=',', encoding='utf-8')
df.head()

PROF           VP  FACIES           VS         GR    POCO
0  3103.0164  4392.102539    85.0  2491.250244  16.139494  poco_1
1  3103.1688  4368.245117    85.0  2502.714111  16.530527  poco_1
2  3103.3212  4354.002930    85.0  2517.204346  16.491985  poco_1
3  3103.4736  4349.213867    85.0  2529.218994  16.053066  poco_1
4  3103.6260  4354.245606    85.0  2535.076172  15.923628  poco_1

In [ ]:
df.shape

(23426, 6)

In [ ]:
df['FACIES'].value_counts()

85.0    19756
82.0     1670
87.0     1580
81.0      420
Name: FACIES, dtype: int64

In [ ]:
df.dtypes

PROF      float64
VP        float64
FACIES    float64
VS        float64
GR        float64
POCO       object
dtype: object

In [ ]:
le = LabelEncoder()

df['POCO'] = le.fit_transform(df['POCO'])
df

PROF           VP  FACIES           VS         GR  POCO
0      3103.0164  4392.102539    85.0  2491.250244  16.139494     0
1      3103.1688  4368.245117    85.0  2502.714111  16.530527     0
2      3103.3212  4354.002930    85.0  2517.204346  16.491985     0
3      3103.4736  4349.213867    85.0  2529.218994  16.053066     0
4      3103.6260  4354.245606    85.0  2535.076172  15.923628     0
...          ...          ...     ...          ...        ...   ...
23421  4845.2532  5594.003906    82.0  3157.704346  14.272353     1
23422  4845.4056  5594.003906    82.0  3157.704346  17.985367     1
23423  4845.5580  5594.003906    82.0  3157.704346  23.278063     1
23424  4845.7104  5594.003906    82.0  3157.704346  27.874161     1
23425  4845.8628  5548.511231    82.0  3157.704346  22.994799     1

[23426 rows x 6 columns]

In [ ]:
target = df.pop("FACIES")

df = pd.concat([df, target], axis=1)

df.head()

PROF           VP           VS         GR  POCO  FACIES
0  3103.0164  4392.102539  2491.250244  16.139494     0    85.0
1  3103.1688  4368.245117  2502.714111  16.530527     0    85.0
2  3103.3212  4354.002930  2517.204346  16.491985     0    85.0
3  3103.4736  4349.213867  2529.218994  16.053066     0    85.0
4  3103.6260  4354.245606  2535.076172  15.923628     0    85.0

In [ ]:
target.shape

(23426,)

In [ ]:
df

PROF           VP           VS         GR  POCO  FACIES
0      3103.0164  4392.102539  2491.250244  16.139494     0    85.0
1      3103.1688  4368.245117  2502.714111  16.530527     0    85.0
2      3103.3212  4354.002930  2517.204346  16.491985     0    85.0
3      3103.4736  4349.213867  2529.218994  16.053066     0    85.0
4      3103.6260  4354.245606  2535.076172  15.923628     0    85.0
...          ...          ...          ...        ...   ...     ...
23421  4845.2532  5594.003906  3157.704346  14.272353     1    82.0
23422  4845.4056  5594.003906  3157.704346  17.985367     1    82.0
23423  4845.5580  5594.003906  3157.704346  23.278063     1    82.0
23424  4845.7104  5594.003906  3157.704346  27.874161     1    82.0
23425  4845.8628  5548.511231  3157.704346  22.994799     1    82.0

[23426 rows x 6 columns]

## **ATRIBUTOS PREVISORES E ALVO**

In [ ]:
previsores = np.c_[df.iloc[:, 1].values, df.iloc[:, 2:4].values]

In [ ]:
previsores

array([[4392.1025391 , 2491.2502441 ,   16.13949394],
       [4368.2451172 , 2502.7141113 ,   16.53052712],
       [4354.0029297 , 2517.2043457 ,   16.49198532],
       ...,
       [5594.0039063 , 3157.7043457 ,   23.27806282],
       [5594.0039063 , 3157.7043457 ,   27.87416077],
       [5548.5112305 , 3157.7043457 ,   22.99479866]])

In [ ]:
previsores.shape

(23426, 3)

In [ ]:
alvo = df.iloc[:, -1].values

In [ ]:
alvo

array([85., 85., 85., ..., 82., 82., 82.])

In [ ]:
alvo.shape

(23426,)

## **Análise das escalas dos atributos (Escalonamento)**

In [ ]:
df.describe()

PROF            VP            VS            GR          POCO  \
count  23426.000000  23426.000000  23426.000000  23426.000000  23426.000000   
mean    3986.543137   4539.864054   2520.558822     15.685612      0.492700   
std      516.587381    305.610356    184.192511     19.466806      0.499957   
min     3083.814000   3025.522217   1467.370239      1.124120      0.000000   
25%     3539.642400   4493.961792   2517.390381      8.619925      0.000000   
50%     3985.869600   4525.891602   2544.662720     11.447866      0.000000   
75%     4432.096800   4550.856934   2569.796631     13.016943      1.000000   
max     4948.885200   6025.330566   3157.704346    245.754974      1.000000   

             FACIES  
count  23426.000000  
mean      84.849313  
std        1.084244  
min       81.000000  
25%       85.000000  
50%       85.000000  
75%       85.000000  
max       87.000000

In [ ]:
from sklearn.preprocessing import StandardScaler
previsores_esc = StandardScaler().fit_transform(previsores)

In [ ]:
previsores_esc

array([[-0.48350675, -0.15912266,  0.0233162 ],
       [-0.56157325, -0.09688283,  0.04340381],
       [-0.60817668, -0.01821218,  0.04142389],
       ...,
       [ 3.44936724,  3.45920212,  0.39002871],
       [ 3.44936724,  3.45920212,  0.62613298],
       [ 3.30050564,  3.45920212,  0.37547726]])

In [ ]:
previsoresdf = pd.DataFrame(previsores_esc)
previsoresdf

0         1         2
0     -0.483507 -0.159123  0.023316
1     -0.561573 -0.096883  0.043404
2     -0.608177 -0.018212  0.041424
3     -0.623847  0.047018  0.018876
4     -0.607383  0.078818  0.012227
...         ...       ...       ...
23421  3.449367  3.459202 -0.072600
23422  3.449367  3.459202  0.118140
23423  3.449367  3.459202  0.390029
23424  3.449367  3.459202  0.626133
23425  3.300506  3.459202  0.375477

[23426 rows x 3 columns]

In [ ]:
previsoresdf.describe()

0             1             2
count  2.342600e+04  2.342600e+04  2.342600e+04
mean   7.279529e-18  2.038268e-15 -4.853020e-17
std    1.000021e+00  1.000021e+00  1.000021e+00
min   -4.955245e+00 -5.717991e+00 -7.480325e-01
25%   -1.502019e-01 -1.720216e-02 -3.629685e-01
50%   -4.572080e-02  1.308653e-01 -2.176955e-01
75%    3.597101e-02  2.673228e-01 -1.370911e-01
max    4.860759e+00  3.459202e+00  1.181880e+01

## **Codificação de variáveis categóricas**

### **LabelEncoder: transformação de variáveis categóricas em numéricas**


In [ ]:
df.head()

PROF           VP           VS         GR  POCO  FACIES
0  3103.0164  4392.102539  2491.250244  16.139494     0    85.0
1  3103.1688  4368.245117  2502.714111  16.530527     0    85.0
2  3103.3212  4354.002930  2517.204346  16.491985     0    85.0
3  3103.4736  4349.213867  2529.218994  16.053066     0    85.0
4  3103.6260  4354.245606  2535.076172  15.923628     0    85.0

In [ ]:
previsores2 = np.c_[df.iloc[:, 1].values, df.iloc[:, 2:4].values]
previsores2

array([[4392.1025391 , 2491.2502441 ,   16.13949394],
       [4368.2451172 , 2502.7141113 ,   16.53052712],
       [4354.0029297 , 2517.2043457 ,   16.49198532],
       ...,
       [5594.0039063 , 3157.7043457 ,   23.27806282],
       [5594.0039063 , 3157.7043457 ,   27.87416077],
       [5548.5112305 , 3157.7043457 ,   22.99479866]])

In [ ]:
alvo2 = df.iloc[:, -1].values.copy()
alvo2

array([85., 85., 85., ..., 82., 82., 82.])

In [ ]:
alvo2.shape

(23426,)

### **Base de treino e teste**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores_esc, alvo, test_size = 0.3, random_state = 0)

In [ ]:
x_treino.shape


(16398, 3)

In [ ]:
x_teste.shape

(7028, 3)

In [ ]:
y_treino.shape

(16398,)

In [ ]:
y_teste.shape

(7028,)

# **Auto ML**

In [ ]:
automl = AutoSklearnClassifier(time_left_for_this_task=120, 
                              per_run_time_limit=30
                               )
# Init training
automl.fit(x_treino, y_treino)
     

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      per_run_time_limit=30, time_left_for_this_task=120)

In [ ]:
print(automl.leaderboard())
#Modelos Avaliados

          rank  ensemble_weight               type      cost   duration
model_id                                                               
2            1             0.18      random_forest  0.051183  12.547808
14           2             0.12        extra_trees  0.053400   7.357938
10           3             0.06      random_forest  0.053954  12.687183
13           4             0.10  gradient_boosting  0.055248   2.683214
5            5             0.02                mlp  0.058389  11.037470
4            6             0.14      random_forest  0.061160  14.591132
7            7             0.04           adaboost  0.115299   2.019455
9            8             0.22           adaboost  0.120843   7.468844
11           9             0.02                mlp  0.153178   3.213112
8           10             0.08                lda  0.156135   1.217885
12          11             0.02                qda  0.156135   0.849038


In [ ]:
 automl.leaderboard(ensemble_only=True)
 #Modelos utilizados no conjunto final

rank  ensemble_weight               type      cost   duration
model_id                                                               
2            1             0.18      random_forest  0.051183  12.547808
14           2             0.12        extra_trees  0.053400   7.357938
10           3             0.06      random_forest  0.053954  12.687183
13           4             0.10  gradient_boosting  0.055248   2.683214
5            5             0.02                mlp  0.058389  11.037470
4            6             0.14      random_forest  0.061160  14.591132
7            7             0.04           adaboost  0.115299   2.019455
9            8             0.22           adaboost  0.120843   7.468844
11           9             0.02                mlp  0.153178   3.213112
8           10             0.08                lda  0.156135   1.217885
12          11             0.02                qda  0.156135   0.849038

In [ ]:
automl.score(x_treino, y_treino)

0.9662763751677034

In [ ]:
automl.score(x_teste, y_teste)


0.9519066590779738

In [ ]:
import sklearn
predictions = automl.predict(x_teste)
print("Accuracy score:", sklearn.metrics.accuracy_score(y_teste, predictions))

Accuracy score: 0.9519066590779738


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(classification_report(y_teste, predictions))

              precision    recall  f1-score   support

        81.0       0.82      0.74      0.78       141
        82.0       0.92      0.82      0.87       500
        85.0       0.97      0.98      0.98      5919
        87.0       0.79      0.79      0.79       468

    accuracy                           0.95      7028
   macro avg       0.88      0.83      0.85      7028
weighted avg       0.95      0.95      0.95      7028



In [ ]:
automl.predict(x_treino)

array([85., 85., 85., ..., 85., 85., 85.])

In [ ]:
previsores


array([[4392.1025391 , 2491.2502441 ,   16.13949394],
       [4368.2451172 , 2502.7141113 ,   16.53052712],
       [4354.0029297 , 2517.2043457 ,   16.49198532],
       ...,
       [5594.0039063 , 3157.7043457 ,   23.27806282],
       [5594.0039063 , 3157.7043457 ,   27.87416077],
       [5548.5112305 , 3157.7043457 ,   22.99479866]])

#Regressão AutoML


In [ ]:
import autosklearn.regression

In [ ]:
autosklearn_regressor = autosklearn.regression.AutoSklearnRegressor(
    time_left_for_this_task=240,
    per_run_time_limit=60,
)

autosklearn_regressor.fit(X_train, y_train, feat_type=feature_types)
Exemplo para regressão


In [ ]:
(X_train.shape,y_train.shape,X_test.shape, y_test.shape  )

In [ ]:
print(autosklearn_regressor.leaderboard())

In [ ]:
from sklearn.metrics import mean_absolute_error as mae

mae(y_train, autosklearn_regressor.predict(X_train)), mae(y_test, autosklearn_regressor.predict(X_test))

In [ ]:
autosklearn_regressor.predict(X_train)
